### ISSUE TITLE
Endless loop in project.tracks

### ISSUE THREAD

**Issue by chabErch** [RomeoDespres/reapy#40]
I tried to use a simple pass through tracks 

```python
import reapy

project = reapy.Project()
for track in project.tracks:
    print(track.GUID)
```

and got an endless loop

> (GUID*)0x000000000279C7C0
> (GUID*)0x00000000027F0430
> (GUID*)0x00000000028028A0
> (GUID*)0x0000000002814D10
> (GUID*)0x000000000279C7C0
> (GUID*)0x000000000279C7C0
> (GUID*)0x000000000279C7C0
> ...

but reaper project contains only four tracks.

Am I doing something wrong?

**Comment by chabErch** [comment]
It might be useful to implement `__iter__` in core classes to get something like this:

```python
project = reapy.Project()
for track in project:
    for item in track:
        for take in item:
            foo(take)
```

**Comment by RomeoDespres** [comment]
Hmmm I don't think the problem is on your side... I'll take a look asap!

**Comment by RomeoDespres** [comment]
Problem solved, I'll let you know when the new version is ready on PyPi. About your suggestion: I can see that it would be faster to write, but I am not sure it is pefectly clear who contains who. For instance, why should `iter(project)` refer to `project.tracks` rather than `project.items`? And why should `iter(track)` refer to `track.items` rather than `tracks.fxs`? I feel for the sake of clarity it's better to keep it the current way:
```python
for track in project.tracks:
    for item in track.items:
        for take in item.takes:
            foo(take)
```

**Comment by RomeoDespres** [comment]
The update is avilable. Sorry for the delay...!
