### ISSUE TITLE
command-line installation

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#61]
I don't have time for that right now, but I can forget the steps:

- make `argparse` for the `__main__.py`
- make cross-platform python library lookup, for Linux it is:
    ```Python
    dir_ = pathlib.Path('/usr/lib/x86_64-linux-gnu')
    so = list(dir_.glob('libpython3*.so'))[0]
    ```
- make reaper resource folder lookup (God knows, how, maybe take from argparce)
- add `dir_` to the `'reaper.ini': 'REAPER', 'pythonlibpath64'`
- add `so` to the `'reaper.ini': 'REAPER', 'pythonlibdll64'`
- add line ```SCR 4 0 RS51d805a68ee3c2516cf4d3dc757e5fb67e3719df "Custom: activate_reapy_server.py" {activate_server_path}``` to the  `reaper-kb.ini`
- somehow run this action (OSC?, register startup somewhere?)

I think, I'll make nails-made solution for Linux today during my CI research, but we'll need to think about making it cross-platform

**Comment by teetow** [comment]
This would be great. I can help with the Windows platform, I've made a bootstrapper for my own tool that includes installing Reapy. 

We've had some brief conversations about this in https://github.com/RomeoDespres/reapy/issues/35, but I can probably write up something a bit more extensive later.

**Comment by RomeoDespres** [comment]
Good to see someone is looking into this! Just for your information, I've seen it is possible to run post-install hooks with setuptools (see [here](https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools) for instance). Ideally, I'd love the full installation (and uninstallation!) process to simply be `pip (un)install python-reapy`.

**Comment by Levitanus** [comment]
> post-install hooks with setuptools

I'm afraid of using input() inside post-instal hooks. For example, inside Docker it's really problem to make something that retrieving user input. And `pip install <command-line arguments>` also not the thing you usually use. Is there another way of specifying Reaper resource folder location or not — I don't know at the moment. But if is — it's really very verbose solution.

Anyway, this is task not for a cup of coffee, so we have time for the investigation :)

**Comment by RomeoDespres** [comment]
In our previous discussion (#35), @teetow was arguing as follows:
> 
> I just assume them [`reaper.ini` and `reaper-kb.ini`] to be in `~/AppData/Roaming/REAPER/` since I don't recall that being something user configurable. My users are all on Windows, but I hope it'd be doable to figure out the corresponding folders on other platforms.

Do you think that is not true? I'm especially wondering about portable installs of REAPER.

**Comment by Levitanus** [comment]
> I'm especially wondering about portable installs of REAPER

At least.
On Linux there are two folders which are can be chosen during the full installation: `/opt/Reaper/<God knows, I use the option 2>` or `~/.config/Reaper/` which is somehow linked with the `/opt/Reaper/` too.
Maybe there is a point to look at the usual places, then request user input.

**Comment by RomeoDespres** [comment]
Nice to know! It's great that you use Linux because I have no idea how things are set up there. I'd be surprised though if the post-install setuptools hooks can not receive user input; after all, they're ran in a standard terminal aren't they?

**Comment by dimentorium** [comment]
Hi all,
just started to use Reapy a bit more in my Preset Manager, but definately agree to teetow that for Users (people not wanting to program), an installer would be helpful to make it easy to use.
I just tested today on Windows the following. Python has the embeddable zip, which is knd of a portable installation. I copied this on a computer without Python, linked Reaper to it and manually copied Reapy in. That works.
So what do you think about an installer that, unzips a ready to use archive, edits the Reaper ini and adds the dist api calls. Than I or others can create small Python executables for users much easier.

Will try to dig a bit more into this

**Comment by dimentorium** [comment]
So first try for installer with REAPY and portable Python for Windows is available, but not yet tested a lot. Anyone interested in having a look? Its more a wizard with Python and tkinter to make the installation of REAPY easier for non programmers. Code is in the repo
https://github.com/dimentorium/PresetManager

**Comment by RomeoDespres** [comment]
@dimentorium I don't get it, you talk about a wizard and a portable Python, but when I read your README you just seem to list standard installation instructions (install the normal Python, then reapy with pip, then enable distant API). What am I missing?

**Comment by dimentorium** [comment]
@RomeoDespres , you are missing that I am very lazy in documenting ;-)
And its the first time I am working on an open source project. 
The installer source is in the folder you mention.
The idea is the following:
- Detect Reaper installation (I do not bundle Reaper in there)
- Extract the portable Python installation with included REAPY (see the zip file in build folder) https://github.com/dimentorium/PresetManager/tree/master/Build/Installer/data
- Set the keys in the ini File. This does not yet work fully, so still manual check is needed
- Guide the user in adding REAPY server into Reaper
- Check if REAPY is working by importing and sending a console command
- Unzip my Preset Manager Application

I think there are two use cases:
- Mine is User Centric, so for people who want to use prebuilt tools. Benefit of the portable Python is that they do not need to install anything else, it keeps everything small and you can get them Python Applications
- Second one would be developer centric where you help how to install everything into a full Python environment, or better create a venv for the REAPY server to make sure Reaper does not crash

Hope that helps

**Comment by RomeoDespres** [comment]
Thanks for the details @dimentorium, it will be of great help to achieve good setup tools in reapy.

Fyi, I've created a branch called [improved-setup](/RomeoDespres/reapy/tree/improved-setup) in which to build these tools. I've added a function [`reapy.config.get_python_shared_library()`](/RomeoDespres/reapy/blob/improved-setup/reapy/config/shared_library.py#L146) that is supposed to return path to Python dll/dylib/so in a cross-platform way. As mentioned in the file it's mostly a modified version of existing scripts found on GitHub. I've tested it with several Python version on Windows, OSX and Ubuntu and it worked well in all cases. I guess it will fail sometimes, but I still hope it can be a good step forward on the path to making reapy setup easier.

**Comment by dimentorium** [comment]
@RomeoDespres , sounds good! I want to spend some time on the weekend for the installer and will have a look. FYI had the first tester in the Reaper forum who worked with the installer and got everything up and running with my Preset Manager

**Comment by RomeoDespres** [comment]
Hi all,

The aforementioned [`improved_setup`](https://github.com/RomeoDespres/reapy/tree/improved-setup) branch now has the API to automate setup as much as possible. The new way to install reapy is:

1. `$ pip install python-reapy`
2. Open REAPER.
3. `$ python -c "import reapy; reapy.configure_reaper()"`
4. Restart REAPER.

Its main entry point is [`reapy.configure_reaper()`](https://github.com/RomeoDespres/reapy/blob/improved-setup/reapy/config/config.py#L165). Running it will perform all steps required to make reapy usable from outside REAPER:

1. Enable usage of Python for ReaScripts.
2. Fill in path to python shared library (.dll, .dylib or .so).
3. Add a web interface on port 2307 to listen to reapy connections.
4. Add the ReaScript `reapy.reascripts.activate_reapy_server` to the *Actions* list.
5. Add the name of this action to REAPER external state.

All of the steps above are only performed if needed. Thus, calling the function twice is harmless.

There is one subtlety that should be pointed. The function is supposed to work for both portable and normal installs or REAPER. However, detection of REAPER resource path for portable installs only works if REAPER is currently running, because in this case reapy will find the path to the REAPER executable (which is the same as the resource path) in the list of currently alive processes of the OS. All this to say: users have to manually open REAPER to complete the setup with `configure_reaper()`. I haven't been able to find another way to handle portable installs.

However, there are cases in which you can use the function without opening REAPER:
1. Assuming the user has a non-portable install, `reapy.configure_reaper(detect_portable_install=False)` will work as expected even if REAPER is closed.
2. Assuming you know the path to the portable install (e.g. if you bundle your own copy of REAPER), `reapy.configure_reaper(resource_path='path/to/portable/install')` will also work as expected even if REAPER is closed.

Does this API look good to you? Please share your thoughts. I don't want to make this

**Comment by Levitanus** [comment]
Looks very promising!
I'll test on the week

**Comment by dimentorium** [comment]
Cool idea!
Just two comments/ideas:
- I had the case, that in my INI fil the section was named "REAPER" instead of "reaper", which caused errors, thats why I switched to "Config.sections()[0]" instead
- Can you run a tkinter select folder "filedialog.askdirectory(title="Select folder")" in the file to ask the user for a portable path? That would be Python without any addons and cross platform

**Comment by Levitanus** [comment]
> Can you run a tkinter select folder "filedialog.askdirectory(title="Select folder")" in the file to ask the user for a portable path?

I opposite to any kind of required (especially, GUI) user-interaction, as it breaks things we even didn't think about). Still, here is walking idea of unit-tests and deployment environment for reapy, such things makes the realization noticeable harder.

**Comment by dimentorium** [comment]
Good point, absolutely agree!

**Comment by RomeoDespres** [comment]
If I'm correct, the `'REAPER'` vs `'reaper'`problem has already been encountered at the very beginning and is supposed to be taken care of by the [`CaseInsensitiveDict`](https://github.com/RomeoDespres/reapy/blob/improved-setup/reapy/config/config.py#L36) class in the `config` subpackage. Please let me know if it causes trouble while using this new API.

The `tkinter` approach indeed has pros. However the way reapy is installed so far is CLI-only, as for the vast majority of Python packages, and I don't think this should be broken. It would be highly non-standard. Moreover, I'd say it is less user-friendly to ask user to look for a complicated path rather than simply open their favorite REAPER. Finally, the way the API is designed allows you to implement your own GUI-based variant if you wish:

```python
path = filedialog.askdirectory(title="Select folder")
reapy.configure_reaper(resource_path=path)
```
The snippet above does not require user to open REAPER.
